### ISSUE TITLE
the input of mlp

### ISSUE THREAD

**Issue by Philipflyg** [ashawkey/jiif#1]
Great work!

But in model/jiif.py: 79~81
```
q_guide = torch.cat([q_guide_hr, q_guide_hr - q_guide_lr], dim=-1)

inp = torch.cat([q_feat, q_guide, rel_coord], dim=-1)
```

It seems inconsistent with the equation (8) of your paper. In eq.(8), the second input feature is g_i, which is a feature sampled from the **low-resolution** feature map. But in the code, q_guide_hr is used, which is sampled from the **high-resolution** features, corresponding to g_q but not g_i.

**Comment by ashawkey** [comment]
@Philipflyg Hi, you are right! Thanks for spotting this difference. Following the original edgeconv, we should use `x_q = f(g_q, g_q - g_i)` ([reference](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.EdgeConv)), which is consistent with the implementation, but differs from our paper. Since these two formulas both contain the needed information, I think the performance could be similar. I'll do some experiments to verify this later.

**Comment by Philipflyg** [comment]
> @Philipflyg Hi, you are right! Thanks for spotting this difference. Following the original edgeconv, we should use `x_q = f(g_q, g_q - g_i)` ([reference](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.EdgeConv)), which is consistent with the implementation, but differs from our paper. Since these two formulas both contain the needed information, I think the performance could be similar. I'll do some experiments to verify this later.

Thanks. Looking forward to your new experimental results. : )
